### ISSUE TITLE
interruptSwitchEncoder8574 only counts every second detent

### ISSUE THREAD

**Issue by ddd999** [davetcc/IoAbstraction#123]
I am using a generic "HW-040" encoder that I got at my local electronics supply. It is connected through a PCF8574N to an Adafruit Trinket M0.

The interruptSwitchEncoder8574 example sketch (with "repeat switch" and second encoder sections removed) counts up and down as expected when the encoder is rotated back and forth, but the library only registers a change for every second detent.

It seems like there needs to be a way to specify how many pulses per revolution your encoder puts out. Is this possible? I've looked through the library sources and couldn't find an obvious way.

[Link to test sketch](https://github.com/davetcc/IoAbstraction/files/6462399/interruptSwitchEncoder8574.txt)

**Comment by davetcc** [comment]
Interestingly, we test that particular example on the same processor, SAMD. I see one increment for each positive position (Detent) of the encoder. What I mean by that is that if I have a 16 position encoder, I'd have 16 updates. I'll check it again some point today just to be 100% sure, as I have the circuit built already. 

I'm not quite sure I understand the problem, is it that if you had an encoder with 16 detents, you only see 8 updates per full turn?

There are three modes of operation:

* counted acceleration mode where the encoder holds a value between 0..n.
* fixed counted mode where the encoder holds a value between 0..n but always 1-1.
* direction only, where going down is -1, going up is 1.

Hope this helps.

**Comment by ddd999** [comment]
> I'm not quite sure I understand the problem, is it that if you had an encoder with 16 detents, you only see 8 updates per full turn?

Yes, exactly.

[Here](https://leeselectronic.com/en/product/1820-rotary-encoded-breakout-w-edtents.html) is a link to the exact encoder I have. I'm not sure how accurate or useful that description is.

In any case, when I turn the encoder one full revolution, I count 30 detents but only get 15 updates.

I thought it might have had something to do with this line in SwitchInput.cpp:

`#define ONE_TURN_OF_ENCODER 32`

However, changing the number and re-compiling/re-uploading has no effect on the behaviour.

**Comment by davetcc** [comment]
> #define ONE_TURN_OF_ENCODER 32

It's a bit misnamed, what it really means is the maximum-value at which acceleration is applied. IE if the maximum-value is below 32 then don't apply any acceleration.

It certainly sounds like there is a problem there, if you are using 2.0.0, please can you try with V1.7.5? We found a quite critical issue with I2C in 2.0 and are trying to make a release for it later today.

However, I'll dig out my SAMD unit and try it myself. I have a rotary encoder connected to it through a PCF8574.

**Comment by ddd999** [comment]
> It certainly sounds like there is a problem there, if you are using 2.0.0, please can you try with V1.7.5?

I've just tried again with 1.7.5 and I get the same result.

**Comment by davetcc** [comment]
I've just run up a menu project with two rotary encoders connected to a PCF8574, which in turn is connected to an MKR1300 (SAMD) unit. It has two basic 20 turn encoders connected up, and the interrupt line back to the device. It even has a color display too which puts far more latency in there. It has barely missed a single detent position. IE I turn it 1 full turn and my value reduces by 20. I turned two whole revolutions and my value went from 100 down to 60.

Could you provide the circuit diagram or a photo of how you've got it wired up please? 

Our encoder logic is state-machine based, which means that it will only ever register valid transitions, in terms of wiring how long are the wires from the PCF8574 to the device? If they are longer than 10 centimeters you may need pull-up resistors close to the encoder as the PCF8574 would be fairly high impedance even with input pull up.

Do you have another encoder to ensure the unit is not faulty?

![20210512_165745335_iOS (2)](https://user-images.githubusercontent.com/12195465/118016353-32bc7f80-b34d-11eb-8b0a-18534d00d383.jpg)

**Comment by ddd999** [comment]
Apparently, not all encoders are "1 pulse per detent" as I assumed they would all be.

It turns out that I've got a "quarter cycle" encoder (2 detents per pulse), as described here:

https://phpjj.wordpress.com/about-rotary-encodera/

Thanks for your help with investigating this. I can solve this issue for my application by using a different encoder

Maybe at some point down the road there could be support for all three types (quarter, half, and full cycle), although I'm not sure if the the Q and F versions are common enough to warrant it.

More references:
https://www.electronicsweekly.com/blogs/engineer-in-wonderland/quadrature-encoder-wisdom-2017-09/
http://www.bsom.org/wp-content/uploads/2008/05/evq-wtef2515b.jpg
https://github.com/keirf/FlashFloppy/issues/130
