### ISSUE TITLE
New dependancy MISSING? SimpleSpinLock

### ISSUE THREAD

**Issue by tablatronix** [davetcc/IoAbstraction#130]
`IoAbstraction/src/PlatformDeterminationWire.h:10:28: fatal error: SimpleSpinLock.h: No such file or directory`

What is this new dependency?

**Comment by davetcc** [comment]
Please can you check that TaskManagerIO is on the latest version. It’s a helper class in task manager.

**Comment by tablatronix** [comment]
Ah ok thanks, was confused why I could not find it anywhere
