### ISSUE TITLE
Rollover option for encoders set to output value ranges

### ISSUE THREAD

**Issue by mmilesg** [davetcc/IoAbstraction#137]
I suggest a rollover option for setting encoder values such that the value would reset to 0 or to the maximum value defined by a tcMenu item or setEncoderPrecision command when rotating an encoder past the value limits.

Additionally, when using an encoder that has been constrained with setEncoderPrecision and/or a setUserIntention(CHANGE_VALUE) command there is no call to the encoderCallback() function when going **down** from 0 or **up** from maximum. Therefore no user code can be used to manually setCurrentReading(*) at the correct time to create rollover functionality.

**Comment by davetcc** [comment]
Many thanks for helping out in the forum, it is available on master and will be in version 2.1.0 coming soon.
