### ISSUE TITLE
esp32-s3 dont have DAC

### ISSUE THREAD

**Issue by Xekz** [davetcc/IoAbstraction#161]
esp32-s3/IoAbstraction/src/esp32/ESP32AnalogDevice.cpp:11:10: fatal error: driver/dac.h: No such file or directory

**Comment by davetcc** [comment]
Apologies but we don't support that board at the moment, we support S2 but we have not got an S3 board to test with. We'll schedule the work to support it though.

**Comment by davetcc** [comment]
Any pointers on a basic dev board would be helpful.

**Comment by davetcc** [comment]
I’ve ordered an esp32s3 mini as they look interesting. I’m sure like the s2 there will be a lot of incompatibility early on.

**Comment by davetcc** [comment]
Fix now on master, tested on an unexpected maker tiny S3. IoAbstraction and TaskManager tests all pass.

**Comment by davetcc** [comment]
Tested right through to menu creation in tcMenu, all working with encoder too.

**Comment by davetcc** [comment]
Closing as smoke tested on ESP32, ESP32S2 and ESP32S3
