### ISSUE TITLE
serLevelEnabled

### ISSUE THREAD

**Issue by umsmin** [davetcc/IoAbstraction#177]
I try to start with tcMenu but getting on every example in the Arduino IDE 1.8.13 the following error:

`SimpleTest.cpp:98:41: error: 'serLevelEnabled' was not declared in this scope
         if(serLevelEnabled(SER_IOA_DEBUG)) {
`

The Library versions are:

tcMenu                   2.5.0
IOAbstraction         2.5.0
LiquidCristalIO       1.4.3
TaskManagerIO      1.3.5
SimpleCollections  1.2.3

The 
TcMenuDesigner   2.5.0

 It's for the ESP32 and the TFT_eSPI Library from Bodmer. This is only shown when I use the examples. 
On my own Menu only "Rotary Encoder" and "2x8 LCD".

**Comment by davetcc** [comment]
Thanks for the report, it is because IoLogging is turned off, I'll fix this before the release. For now if you want to continue using this version set build flag IO_LOGGING_DEBUG and it would work.
 
I think you're using the developer version of IoAbstraction (2.5.0), Hopefully, this wasn't published anywhere yet. Did you take the master branch or was a package manager serving this up? Quite important, as it shouldn't be released yet as it is effectively untested.

**Comment by davetcc** [comment]
TcMenu latest is 2.5.0
IOAbstraction latest should be 2.4.3 to use the tested version, which if you're new to it I really recommend

**Comment by umsmin** [comment]
Thanks for your replay.
I get all the stuff directly from Github. I will better downgrade it and have a try.

**Comment by davetcc** [comment]
FIX: ensure before next release that this compiles without the debug flag turned on

**Comment by umsmin** [comment]
Now I tried it and it works without the error. But I can't make my own with the Bodmer libraries. I create a simple menu for touch but when I start to "generate code" it will not show me the eSPI option. Where is my mistake?

**Comment by davetcc** [comment]
Make sure the platform in code generator (top section of the generator dialog)is set to one of :

ARDUINO_32
ARDUINO_ESP8266
ARDUINO_ESP32
STM32DUINO

These are the only devices that the underlying library supports

**Comment by umsmin** [comment]
Yes it's on 

ARDUINO_ESP32

In your examples you don't have a touch menu with eSPI library from Bodmer?

**Comment by davetcc** [comment]
We have plugin for Bodmers' TFT_eSPI display, but we've tended to use other input libraries. There are a few touch plugins, one for directly managing resistive touch input, and then another for common touch libraries.

**Comment by umsmin** [comment]
How can I use it. The Bodmer are for me at this moment the best working ones. How can I add plugins for the different libraries?

**Comment by davetcc** [comment]
I mean you could take a look at how we do the other touch plugins and try to write something similar for that library. Effectively you just need to plugin the X, Y and Z(force) into the IoAbstraction touch facilities. They are documented to some extent here: https://www.thecoderscorner.com/products/arduino-libraries/io-abstraction/touch-screen-support/

Effectively, you'd want to take a look how the two existing touch plugins work, and write your own touch interrogator as per the docs above. You could either do this as a plugin, or alternatively set the input code generator to "No Input" and just write your own code for it in setup.

Writing a plugin is quite straightforward. It's in XML format, here: https://github.com/davetcc/tcMenu/tree/master/xmlPlugins

**Comment by umsmin** [comment]
Okay thank. But your plugins for the displays are not shown in the tcMenu Designer. Only the LCD-plugin. where is my mistake I made?

**Comment by davetcc** [comment]
The only reason I can think of would be the platform is not right. Have you clicked on the image to select a different plugin?

**Comment by umsmin** [comment]
Yes sure. 
As input is the rotary encoder.
As display is the LCD shield on I2C.
And for remote is no remote capability.

Must I put the plugins in a sub folder from designer?

**Comment by davetcc** [comment]
There should be nothing to do other than select the plugins you want to use, those sound like the defaults, have you read through the getting started guide? Here's documentation about the code generator:

https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/code-generator-and-plugins-guide/

I misunderstood before and thought you were asking how to write your own plugin, if all you want is to use the TFT_eSPI plugin, just click the change button on the left of the display plugin and change it to the one you want. Code generator will do the rest. Apologies for complicating things.

**Comment by umsmin** [comment]
Where must be the plugins located? I don't see them anywhere. Not in the tcMenu Designer program folder or any sub folders. Also not in the Arduino -> libraries -> tcMenu folders.

The page behind the link I read and know how it works, but the plugins will never been shown.

Yes I only want to use it, don't make own plugins at this moment. I have an application and my menu system is unusable so I looked for a good one on the touch display.

**Comment by davetcc** [comment]
This guide explains how to get started 

https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/code-generator-and-plugins-guide/

**Comment by umsmin** [comment]
Yes I know and read it not only once. But there is not shown where are the plugins located.

**Comment by davetcc** [comment]
Ok by default the plugins are installed into the .tcmenu/plugins folder from your home directory. They would normally be put there at first start up by the UI.

They must be there as you wouldn’t even see any plugins at all otherwise. The package we create has all the plugins packaged with it.

**Comment by umsmin** [comment]
They all there. I start the tcMenu Designer as normally user or administrator but nothing helps. He don't use them

**Comment by davetcc** [comment]
If you can send your logs (in that .tcMenu directory under logs)  I’ll take a look at them tomorrow. There must be something strange going on there.

**Comment by umsmin** [comment]
The only thing that's not working is the touch from the eSPI library display. The menu is now shown but wich input plugin can I use?

**Comment by davetcc** [comment]
No problem I wanted to make sure there wasn’t a problem somewhere. For the input plugin you can either use the Arduino library touch plugin that supports many common libraries and touch interfaces. Or you can use the resistive touch plugin if you have the X and Y connectors directly connected.

**Comment by davetcc** [comment]
If you’re using master of IoAbstraction you could pull the latest, I think I fixed that already.

**Comment by umsmin** [comment]
I use this display 

[https://www.amazon.de/gp/product/B08SBTBRZV/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1](url)

and it works fine with eSPI library from Bodmer. 
The resistive touch plugin don't work because it has his own controller. 

The display is ILI9341
Touch is XPT2046

Adafruit libraries are not working.

It use the SPI interface for display and touch together. Only the CS_DISP and CS_TOUCH are on separate pins.

**Comment by davetcc** [comment]
Yes the "FT6206/XPT2046 touch screen plugin that provides integration with library" plugin should work, as long as you install the XPT2046 library by Paul Stoffregen. It just needs the CS pin to be defined in order to work.
