### ISSUE TITLE
Missing image in Switches and rotary encoder documentation

### ISSUE THREAD

**Issue by leosdad** [davetcc/IoAbstraction#195]
There is a missing image in [this page](https://www.thecoderscorner.com/products/arduino-libraries/io-abstraction/switches-rotary-encoder-documentation/). The relevant HTML code is:

<img src="/images/electronics/arduino/ioAbstraction/pullup-and-pulldown-switches.png" alt="Pull down &amp; pull up examples">

**Screenshots**

![chrome_15-18-23_18-54-58](https://github.com/davetcc/IoAbstraction/assets/7026091/dfd9503a-58c4-42a1-98c8-c36bf23b10c1)

**Comment by davetcc** [comment]
Thanks for pointing out, a few months back we open-sourced the Arduino libraries documentation part of the site - https://github.com/davetcc/library-documentation and there were a few shared images between both parts of the site, we thought they were all updated but I think there's still a few that were missed, I'll fix that.
