### ISSUE TITLE
Support on release callback function

### ISSUE THREAD

**Issue by klaudiusz223** [davetcc/IoAbstraction#32]
Adding support of on release callback function will simplify detecting switch releasing. My implementation: e5d9fdd70128f7d345f5e1e1c8c7c2ced655509b

**Comment by davetcc** [comment]
Implementation looks good. I will extend the unit tests to test this case and get onto master. Hopefully this week. Many thanks for this.

**Comment by klaudiusz223** [comment]
Thank you. I realized that information about button holding could be useful after releasing it. I implemented this f27de9ecf4aaebca35ab2798fd97e1190e62c5c8

**Comment by davetcc** [comment]
Excellent I’ll merge that one instead once I get a few minutes in my office this week.  Many thanks, Dave.

**Comment by davetcc** [comment]
Please could you turn the changes into a pull request when you have a moment, as I don't have permission to pull the changes from the branch.
