### ISSUE TITLE
Allowing MAX_KEYS to be set during build

### ISSUE THREAD

**Issue by klaudiusz223** [davetcc/IoAbstraction#33]
Enabling MAX_KEYS setting during compilation to prevent the need to modify library files.

```
#ifndef MAX_KEYS
#define MAX_KEYS 4
#endif
```
Probably the same with MAX_ALLOWABLE_DELEGATES

**Comment by davetcc** [comment]
Agreed. Many Thanks for this, I’ll try and merge it in to master this week.
