### ISSUE TITLE
tasks array in TaskManager not taking DEFAULT_TASK_SIZE into account causing crashes

### ISSUE THREAD

**Issue by klaudiusz223** [davetcc/IoAbstraction#36]
This line 
https://github.com/davetcc/IoAbstraction/blob/86cc49202c1795f9d25f246869dcc33ea5f258ab/src/TaskManager.h#L139

should be 
`	TimerTask tasks[DEFAULT_TASK_SIZE];`

**Comment by davetcc** [comment]
Critical bug fix will be applied and release ASAP. Thanks for reporting,

**Comment by davetcc** [comment]
Closed, released in 1.3.1
