### ISSUE TITLE
Rotary encoder acceleration should be configurable 

### ISSUE THREAD

**Issue by Express1** [davetcc/IoAbstraction#73]
I use the buttoRotaryEncoder example for the ioAbstraction library (latest library version, arduino nano).
Is working as expected but I have a question regarding the encoder - when turned really slow will go in a normal sequence like 1,2,3,4. If turned faster will skip - 12,22,32.
So it looks like some sort of acceleration is implemented. Is there a way to turn this off?
I did look a little bit at the docs but I was not able to find anything related.

Thank you,
Radu

**Comment by davetcc** [comment]
Yes there is acceleration implemented in the encoder.  Unfortunately it is presently not configurable. I will add this in the next release.  

However it is very easy to change the code temporarily until the next release. 

Just go to src /SwitchInput.cpp and change the whole body of the following method to just return 1. 

HardwareRotaryEncoder::amountFromChange(unsigned long change)

**Comment by Express1** [comment]
Based on your reply I modified src /SwitchInput.cpp and is working as expected.
on top#define NOACCEL
....
 
int HardwareRotaryEncoder::amountFromChange(unsigned long change) {#if defined(NOACCEL)<------>// no accel<------>return 1;#else defined(NOACCEL)<------>if(change > 250000 || maximumValue < ONE_TURN_OF_ENCODER) return 1;
<------>if(change > 120000) return 2;<------>else if (change > 70000) return 4;<------>else if (change > 30000) return 6;<------>else return 10;#endif defined(NOACCEL)}



    On Wednesday, November 6, 2019, 05:49:39 AM EST, Dave Cherry <notifications@github.com> wrote:  
 
 
Yes there is acceleration implemented in the encoder. Unfortunately it is presently not configurable. I will add this in the next release.

However it is very easy to change the code temporarily until the next release.

Just go to src /SwitchInput.cpp and change the whole body of the following method to just return 1.

HardwareRotaryEncoder::amountFromChange(unsigned long change)

**Comment by davetcc** [comment]
Good news I’ll get another release out soon where acceleration is optional.

**Comment by davetcc** [comment]
Will be in release 1.4.11 today

**Comment by davetcc** [comment]
HW rotary encoder has new function: 

`void setAccelerationMode(HWAccelerationMode mode) { accelerationMode =  mode; }`

This has three values:

`
    /** No acceleration, no matter how fast the encoder is turned */
    HWACCEL_NONE,
    /** The default, accelerates based on how fast the encoder is turned */
    HWACCEL_REGULAR,
    /** Slower acceleration than above is applied */ 
    HWACCEL_SLOWER
`
